-- ----------------------------------------------------------------------------
-- Milestone 2 — destination zone seed (195 countries, FR + EN names).
--
-- Every country is seeded into the single zone 'Worldwide', which is the column
-- name the existing plans already use in `catalogue.pricing_rules.pricingColumns`.
-- Pricing therefore behaves EXACTLY as it does today until the client supplies a
-- real zone mapping; at that point the superadmin reassigns countries to new
-- zones and the pricing engine picks the matching column automatically.
--
-- Generated from frontend/src/constants/countries.ts, with French names resolved
-- through i18n-iso-countries (the same source the web UI uses for its labels),
-- so chat copy and web copy can never drift apart.
--
-- SAFETY: INSERT IGNORE against a UNIQUE country_code. Re-running changes nothing
-- and, critically, never overwrites a zone the operator has already reassigned.
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO `destination_zones` (`country_code`, `country_name_en`, `country_name_fr`, `zone`) VALUES
  ('AF', 'Afghanistan', 'Afghanistan', 'Worldwide'),
  ('AL', 'Albania', 'Albanie', 'Worldwide'),
  ('DZ', 'Algeria', 'Algérie', 'Worldwide'),
  ('AD', 'Andorra', 'Andorre', 'Worldwide'),
  ('AO', 'Angola', 'Angola', 'Worldwide'),
  ('AR', 'Argentina', 'Argentine', 'Worldwide'),
  ('AM', 'Armenia', 'Arménie', 'Worldwide'),
  ('AU', 'Australia', 'Australie', 'Worldwide'),
  ('AT', 'Austria', 'Autriche', 'Worldwide'),
  ('AZ', 'Azerbaijan', 'Azerbaïdjan', 'Worldwide'),
  ('BS', 'Bahamas', 'Bahamas', 'Worldwide'),
  ('BH', 'Bahrain', 'Bahreïn', 'Worldwide'),
  ('BD', 'Bangladesh', 'Bangladesh', 'Worldwide'),
  ('BB', 'Barbados', 'Barbade', 'Worldwide'),
  ('BY', 'Belarus', 'Biélorussie', 'Worldwide'),
  ('BE', 'Belgium', 'Belgique', 'Worldwide'),
  ('BZ', 'Belize', 'Belize', 'Worldwide'),
  ('BJ', 'Benin', 'Bénin', 'Worldwide'),
  ('BT', 'Bhutan', 'Bhoutan', 'Worldwide'),
  ('BO', 'Bolivia', 'Bolivie', 'Worldwide'),
  ('BA', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'Worldwide'),
  ('BW', 'Botswana', 'Botswana', 'Worldwide'),
  ('BR', 'Brazil', 'Brésil', 'Worldwide'),
  ('BN', 'Brunei', 'Brunei Darussalam', 'Worldwide'),
  ('BG', 'Bulgaria', 'Bulgarie', 'Worldwide'),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'Worldwide'),
  ('BI', 'Burundi', 'Burundi', 'Worldwide'),
  ('KH', 'Cambodia', 'Cambodge', 'Worldwide'),
  ('CM', 'Cameroon', 'Cameroun', 'Worldwide'),
  ('CA', 'Canada', 'Canada', 'Worldwide'),
  ('CV', 'Cape Verde', 'Cap-Vert', 'Worldwide'),
  ('CF', 'Central African Republic', 'République Centrafricaine', 'Worldwide'),
  ('TD', 'Chad', 'Tchad', 'Worldwide'),
  ('CL', 'Chile', 'Chili', 'Worldwide'),
  ('CN', 'China', 'Chine', 'Worldwide'),
  ('CO', 'Colombia', 'Colombie', 'Worldwide'),
  ('KM', 'Comoros', 'Comores', 'Worldwide'),
  ('CG', 'Congo', 'République du Congo', 'Worldwide'),
  ('CR', 'Costa Rica', 'Costa Rica', 'Worldwide'),
  ('CI', 'Côte-d''Ivoire', 'Côte-d''Ivoire', 'Worldwide'),
  ('HR', 'Croatia', 'Croatie', 'Worldwide'),
  ('CU', 'Cuba', 'Cuba', 'Worldwide'),
  ('CY', 'Cyprus', 'Chypre', 'Worldwide'),
  ('CZ', 'Czech Republic', 'République Tchèque', 'Worldwide'),
  ('DK', 'Denmark', 'Danemark', 'Worldwide'),
  ('DJ', 'Djibouti', 'Djibouti', 'Worldwide'),
  ('DM', 'Dominica', 'Dominique', 'Worldwide'),
  ('DO', 'Dominican Republic', 'République Dominicaine', 'Worldwide'),
  ('EC', 'Ecuador', 'Équateur', 'Worldwide'),
  ('EG', 'Egypt', 'Égypte', 'Worldwide'),
  ('SV', 'El Salvador', 'El Salvador', 'Worldwide'),
  ('GQ', 'Equatorial Guinea', 'Guinée équatoriale', 'Worldwide'),
  ('ER', 'Eritrea', 'Érythrée', 'Worldwide'),
  ('EE', 'Estonia', 'Estonie', 'Worldwide'),
  ('SZ', 'Eswatini', 'Royaume d''Eswatini', 'Worldwide'),
  ('ET', 'Ethiopia', 'Éthiopie', 'Worldwide'),
  ('FJ', 'Fiji', 'Fidji', 'Worldwide'),
  ('FI', 'Finland', 'Finlande', 'Worldwide'),
  ('FR', 'France', 'France', 'Worldwide'),
  ('GA', 'Gabon', 'Gabon', 'Worldwide'),
  ('GM', 'Gambia', 'Gambie', 'Worldwide'),
  ('GE', 'Georgia', 'Géorgie', 'Worldwide'),
  ('DE', 'Germany', 'Allemagne', 'Worldwide'),
  ('GH', 'Ghana', 'Ghana', 'Worldwide'),
  ('GR', 'Greece', 'Grèce', 'Worldwide'),
  ('GD', 'Grenada', 'Grenade', 'Worldwide'),
  ('GT', 'Guatemala', 'Guatemala', 'Worldwide'),
  ('GN', 'Guinea', 'Guinée', 'Worldwide'),
  ('GW', 'Guinea-Bissau', 'Guinée-Bissau', 'Worldwide'),
  ('GY', 'Guyana', 'Guyana', 'Worldwide'),
  ('HT', 'Haiti', 'Haïti', 'Worldwide'),
  ('HN', 'Honduras', 'Honduras', 'Worldwide'),
  ('HU', 'Hungary', 'Hongrie', 'Worldwide'),
  ('IS', 'Iceland', 'Islande', 'Worldwide'),
  ('IN', 'India', 'Inde', 'Worldwide'),
  ('ID', 'Indonesia', 'Indonésie', 'Worldwide'),
  ('IR', 'Iran', 'Iran', 'Worldwide'),
  ('IQ', 'Iraq', 'Irak', 'Worldwide'),
  ('IE', 'Ireland', 'Irlande', 'Worldwide'),
  ('IL', 'Israel', 'Israël', 'Worldwide'),
  ('IT', 'Italy', 'Italie', 'Worldwide'),
  ('JM', 'Jamaica', 'Jamaïque', 'Worldwide'),
  ('JP', 'Japan', 'Japon', 'Worldwide'),
  ('JO', 'Jordan', 'Jordanie', 'Worldwide'),
  ('KZ', 'Kazakhstan', 'Kazakhstan', 'Worldwide'),
  ('KE', 'Kenya', 'Kenya', 'Worldwide'),
  ('KI', 'Kiribati', 'Kiribati', 'Worldwide'),
  ('XK', 'Kosovo', 'Kosovo', 'Worldwide'),
  ('KW', 'Kuwait', 'Koweït', 'Worldwide'),
  ('KG', 'Kyrgyzstan', 'Kirghizistan', 'Worldwide'),
  ('LA', 'Laos', 'Laos', 'Worldwide'),
  ('LV', 'Latvia', 'Lettonie', 'Worldwide'),
  ('LB', 'Lebanon', 'Liban', 'Worldwide'),
  ('LS', 'Lesotho', 'Lesotho', 'Worldwide'),
  ('LR', 'Liberia', 'Libéria', 'Worldwide'),
  ('LY', 'Libya', 'Libye', 'Worldwide'),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'Worldwide'),
  ('LT', 'Lithuania', 'Lituanie', 'Worldwide'),
  ('LU', 'Luxembourg', 'Luxembourg', 'Worldwide'),
  ('MG', 'Madagascar', 'Madagascar', 'Worldwide'),
  ('MW', 'Malawi', 'Malawi', 'Worldwide'),
  ('MY', 'Malaysia', 'Malaisie', 'Worldwide'),
  ('MV', 'Maldives', 'Maldives', 'Worldwide'),
  ('ML', 'Mali', 'Mali', 'Worldwide'),
  ('MT', 'Malta', 'Malte', 'Worldwide'),
  ('MH', 'Marshall Islands', 'Îles Marshall', 'Worldwide'),
  ('MR', 'Mauritania', 'Mauritanie', 'Worldwide'),
  ('MU', 'Mauritius', 'Maurice', 'Worldwide'),
  ('MX', 'Mexico', 'Mexique', 'Worldwide'),
  ('FM', 'Micronesia', 'Micronésie', 'Worldwide'),
  ('MD', 'Moldova', 'Moldavie', 'Worldwide'),
  ('MC', 'Monaco', 'Monaco', 'Worldwide'),
  ('MN', 'Mongolia', 'Mongolie', 'Worldwide'),
  ('ME', 'Montenegro', 'Monténégro', 'Worldwide'),
  ('MA', 'Morocco', 'Maroc', 'Worldwide'),
  ('MZ', 'Mozambique', 'Mozambique', 'Worldwide'),
  ('MM', 'Myanmar', 'Myanmar', 'Worldwide'),
  ('NA', 'Namibia', 'Namibie', 'Worldwide'),
  ('NR', 'Nauru', 'Nauru', 'Worldwide'),
  ('NP', 'Nepal', 'Népal', 'Worldwide'),
  ('NL', 'Netherlands', 'Pays-Bas', 'Worldwide'),
  ('NZ', 'New Zealand', 'Nouvelle-Zélande', 'Worldwide'),
  ('NI', 'Nicaragua', 'Nicaragua', 'Worldwide'),
  ('NE', 'Niger', 'Niger', 'Worldwide'),
  ('NG', 'Nigeria', 'Nigéria', 'Worldwide'),
  ('KP', 'North Korea', 'Corée du Nord', 'Worldwide'),
  ('MK', 'North Macedonia', 'Macédoine du Nord', 'Worldwide'),
  ('NO', 'Norway', 'Norvège', 'Worldwide'),
  ('OM', 'Oman', 'Oman', 'Worldwide'),
  ('PK', 'Pakistan', 'Pakistan', 'Worldwide'),
  ('PW', 'Palau', 'Palaos', 'Worldwide'),
  ('PS', 'Palestine', 'Palestine', 'Worldwide'),
  ('PA', 'Panama', 'Panama', 'Worldwide'),
  ('PG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'Worldwide'),
  ('PY', 'Paraguay', 'Paraguay', 'Worldwide'),
  ('PE', 'Peru', 'Pérou', 'Worldwide'),
  ('PH', 'Philippines', 'Philippines', 'Worldwide'),
  ('PL', 'Poland', 'Pologne', 'Worldwide'),
  ('PT', 'Portugal', 'Portugal', 'Worldwide'),
  ('QA', 'Qatar', 'Qatar', 'Worldwide'),
  ('RO', 'Romania', 'Roumanie', 'Worldwide'),
  ('RU', 'Russia', 'Russie', 'Worldwide'),
  ('RW', 'Rwanda', 'Rwanda', 'Worldwide'),
  ('KN', 'Saint Kitts and Nevis', 'Saint-Christophe-et-Niévès', 'Worldwide'),
  ('LC', 'Saint Lucia', 'Sainte-Lucie', 'Worldwide'),
  ('VC', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines', 'Worldwide'),
  ('WS', 'Samoa', 'Samoa', 'Worldwide'),
  ('SM', 'San Marino', 'Saint-Marin', 'Worldwide'),
  ('ST', 'Sao Tome and Principe', 'São Tomé-et-Principe', 'Worldwide'),
  ('SA', 'Saudi Arabia', 'Arabie Saoudite', 'Worldwide'),
  ('SN', 'Senegal', 'Sénégal', 'Worldwide'),
  ('RS', 'Serbia', 'Serbie', 'Worldwide'),
  ('SC', 'Seychelles', 'Seychelles', 'Worldwide'),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'Worldwide'),
  ('SG', 'Singapore', 'Singapour', 'Worldwide'),
  ('SK', 'Slovakia', 'Slovaquie', 'Worldwide'),
  ('SI', 'Slovenia', 'Slovénie', 'Worldwide'),
  ('SB', 'Solomon Islands', 'Îles Salomon', 'Worldwide'),
  ('SO', 'Somalia', 'Somalie', 'Worldwide'),
  ('ZA', 'South Africa', 'Afrique du Sud', 'Worldwide'),
  ('KR', 'South Korea', 'Corée du Sud', 'Worldwide'),
  ('SS', 'South Sudan', 'Soudan du Sud', 'Worldwide'),
  ('ES', 'Spain', 'Espagne', 'Worldwide'),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'Worldwide'),
  ('SD', 'Sudan', 'Soudan', 'Worldwide'),
  ('SR', 'Suriname', 'Suriname', 'Worldwide'),
  ('SE', 'Sweden', 'Suède', 'Worldwide'),
  ('CH', 'Switzerland', 'Suisse', 'Worldwide'),
  ('SY', 'Syria', 'Syrie', 'Worldwide'),
  ('TW', 'Taiwan', 'Taïwan', 'Worldwide'),
  ('TJ', 'Tajikistan', 'Tadjikistan', 'Worldwide'),
  ('TZ', 'Tanzania', 'République unie de Tanzanie', 'Worldwide'),
  ('TH', 'Thailand', 'Thaïlande', 'Worldwide'),
  ('TL', 'Timor-Leste', 'Timor-Leste', 'Worldwide'),
  ('TG', 'Togo', 'Togo', 'Worldwide'),
  ('TO', 'Tonga', 'Tonga', 'Worldwide'),
  ('TT', 'Trinidad and Tobago', 'Trinité-et-Tobago', 'Worldwide'),
  ('TN', 'Tunisia', 'Tunisie', 'Worldwide'),
  ('TR', 'Turkey', 'Turquie', 'Worldwide'),
  ('TM', 'Turkmenistan', 'Turkménistan', 'Worldwide'),
  ('TV', 'Tuvalu', 'Tuvalu', 'Worldwide'),
  ('UG', 'Uganda', 'Ouganda', 'Worldwide'),
  ('UA', 'Ukraine', 'Ukraine', 'Worldwide'),
  ('AE', 'United Arab Emirates', 'Émirats Arabes Unis', 'Worldwide'),
  ('GB', 'United Kingdom', 'Royaume-Uni', 'Worldwide'),
  ('US', 'United States', 'États-Unis d''Amérique', 'Worldwide'),
  ('UY', 'Uruguay', 'Uruguay', 'Worldwide'),
  ('UZ', 'Uzbekistan', 'Ouzbékistan', 'Worldwide'),
  ('VU', 'Vanuatu', 'Vanuatu', 'Worldwide'),
  ('VA', 'Vatican City', 'Saint-Siège (Vatican)', 'Worldwide'),
  ('VE', 'Venezuela', 'Venezuela', 'Worldwide'),
  ('VN', 'Vietnam', 'Vietnam', 'Worldwide'),
  ('YE', 'Yemen', 'Yémen', 'Worldwide'),
  ('ZM', 'Zambia', 'Zambie', 'Worldwide'),
  ('ZW', 'Zimbabwe', 'Zimbabwe', 'Worldwide');
